name: movietime
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.0
  url_launcher: ^6.3.0
  flutter_mobx: ^2.2.1+1
  connectivity_plus: ^6.0.5
  fluttertoast: ^8.2.8
  photo_view: ^0.15.0
  shared_preferences: ^2.3.2
  flutter_rating_bar: ^4.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
